-- 1. 제약 조건 잠깐 해제
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_SAFE_UPDATES = 0;

-- 2. 테이블별로 데이터 삭제
DELETE FROM PLAYER_INFO;
DELETE FROM PLAYER_CUSTOM;
DELETE FROM LOGIN_INFO;
DELETE FROM PLAYER_INVENTORY;
-- 필요한 테이블들 계속 추가...

-- 3. 제약 조건 다시 활성화
SET FOREIGN_KEY_CHECKS = 1;
SET SQL_SAFE_UPDATES = 1;